query getCompany($id: Uint!) {
  company(id: $id) {
    id
    name
    employment {
      id
      kind
      status
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}

query getCompanies {
  companies {
    id
    name
    createdAt
    updatedAt
  }
}
