query getDesiredShifts($companyId: Uint!, $fromTime: Time!, $toTime: Time!) {
  desiredShifts(companyId: $companyId, fromTime: $fromTime, toTime: $toTime) {
    id
    since
    till
    employmentId
    createdAt
    updatedAt
  }
}
query getCompanyDesiredShifts(
  $companyId: Uint!
  $fromTime: Time!
  $toTime: Time!
) {
  companyDesiredShifts(
    companyId: $companyId
    fromTime: $fromTime
    toTime: $toTime
  ) {
    id
    since
    till
    employmentId
    employment {
      id
      kind
      status
      worker {
        id
        status
        email
        name {
          firstName
          lastName
        }
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
mutation createDesiredShift($companyId: Uint!, $since: Time!, $till: Time!) {
  createDesiredShift(companyId: $companyId, since: $since, till: $till) {
    id
  }
}
