query getMe {
  me {
    id
  }
}
query getCompanyWorkers($companyId: Uint!) {
  companyWorkers(companyId: $companyId) {
    id
    name {
      firstName
      lastName
    }
  }
}

mutation signUp(
  $email: String!
  $password: String!
  $passwordConfirmation: String!
  $firstName: String!
  $lastName: String!
) {
  signUp(
    email: $email
    password: $password
    passwordConfirmation: $passwordConfirmation
    firstName: $firstName
    lastName: $lastName
  ) {
    id
  }
}
