version: '3.8'

services:
  backend:
    container_name: kintai-backend
    image: kintai-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - 4800:8080
    stdin_open: true
    tty: true
    depends_on:
      - db
    # volumes:
    #   - ./backend:/app
    #   - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime

  frontend:
    container_name: kintai-frontend
    image: kintai-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    # volumes:
    #   - ./frontend:/app
    #   - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime
    ports:
      - 3080:4400
    restart: always
    depends_on:
      - backend

  db:
    container_name: kintai-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kintai_production
    volumes:
      - database:/var/lib/postgresql/data
    #   - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime

volumes:
  database:
