version: '3.8'

services:
  backend:
    container_name: kintai_backend
    image: kintai_backend
    build:
      context: ./backend
    env_file: ./backend/.env.development
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime

  frontend:
    container_name: kintai_frontend
    image: kintai_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    depends_on:
      - backend

  db:
    container_name: kintai_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kintai_development
    volumes:
      - db-data:/var/lib/postgresql/data
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime

volumes:
  db-data:
