version: '3.8'

services:
  backend:
    container_name: kintai-backend
    image: kintai-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    stdin_open: true
    tty: true
    depends_on:
      - db

  frontend:
    container_name: kintai-frontend
    image: kintai-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
    environment:
      - BACKEND_HOST=http://backend:8080
    depends_on:
      - backend

  db:
    container_name: kintai-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kintai_production
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    container_name: kintai-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 54070:3080
      - 54080:4080
    depends_on:
      - backend
      - frontend

volumes:
  database:
