package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"kintai_backend/graph"
	"kintai_backend/graph/model"
)

func (r *queryResolver) CompanyShifts(ctx context.Context, companyID uint) ([]*model.Shift, error) {
	panic(fmt.Errorf("not implemented: CompanyShifts - companyShifts"))
}

func (r *shiftResolver) Employment(ctx context.Context, obj *model.Shift) (*model.Employment, error) {
	panic(fmt.Errorf("not implemented: Employment - employment"))
}

func (r *Resolver) Shift() graph.ShiftResolver { return &shiftResolver{r} }

type shiftResolver struct{ *Resolver }
