package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"kintai_backend/graph/model"
)

func (r *mutationResolver) PushStamp(ctx context.Context, employmentID uint) (*model.Stamp, error) {
	panic(fmt.Errorf("not implemented: PushStamp - pushStamp"))
}
