package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"kintai_backend/domain"
	"kintai_backend/graph/model"
	"kintai_backend/registry"
)

func (r *mutationResolver) SignUp(ctx context.Context, email string, password string, firstName string, lastName string) (*model.Worker, error) {
	panic(fmt.Errorf("not implemented: SignUp - signUp"))
}

func (r *queryResolver) Me(ctx context.Context) (*model.Worker, error) {
	worker, err := currentWorker(ctx)
	if err != nil {
		return nil, nil
	}
	return model.NewWorker(worker), nil
}

func (r *queryResolver) CompanyWorkers(ctx context.Context, companyID uint) ([]*model.Worker, error) {
	registry := registry.GetRegistry()
	workerId, err := currentWorkerId(ctx)
	if err != nil {
		return nil, newError(err, "ログインしてください")
	}
	workers, err := registry.WorkerUseCase().ListCompanyWorkers(*workerId, domain.CompanyID(companyID))
	if err != nil {
		return nil, newError(err, "社員一覧の取得に失敗しました")
	}
	return model.NewWorkers(workers), nil
}
