package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"kintai_backend/graph/model"
	"kintai_backend/registry"
)

func (r *queryResolver) WorkStatus(ctx context.Context, companyID uint) (model.WorkStatus, error) {
	registry := registry.GetRegistry()
	workerId, err := currentWorkerId(ctx)
	if err != nil {
		return "", newError(err, "ログインしてください")
	}
	company, err := GetCompany(ctx, companyID)
	if err != nil {
		return "", newError(err, "会社IDが正しくありません")
	}
	employment, err := registry.EmploymentRepo().Find(company.ID, *workerId)
	if err != nil {
		return "", newError(err, "この会社に属していません")
	}
	workStatus, err := registry.WorkStatusUseCase().Show(employment.ID)
	if err != nil {
		return "", newError(err, "勤怠情報の取得に失敗しました")
	}
	return model.NewWorkStatus(workStatus), nil
}
