package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"kintai_backend/domain"
	"kintai_backend/graph/model"
	"kintai_backend/registry"
)

func (r *queryResolver) WorkStatus(ctx context.Context, companyID uint) (model.WorkStatus, error) {
	registry := registry.GetRegistry()
	workerId, err := currentWorkerId(ctx)
	if err != nil {
		return "", newError(err, "ログインしてください")
	}
	workStatus, err := registry.WorkStatusUseCase().GetCurrentWorkStatus(*workerId, domain.CompanyID(companyID))
	if err != nil {
		return "", newError(err, "勤怠情報の取得に失敗しました")
	}
	return model.NewWorkStatus(*workStatus), nil
}
