version: '3.8'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: postgres14
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kintai_development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
