package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"kintai_backend/auth"
	"kintai_backend/graph"
	"kintai_backend/graph/model"
)

func (r *queryResolver) Me(ctx context.Context) (*model.Worker, error) {
	echoCtx, err := echoContextFromContext(ctx)
	if err != nil {
		return nil, err
	}
	worker, err := auth.CurrentWorker(echoCtx)
	if err != nil {
		return nil, err
	}
	return model.NewWorker(worker), nil
}

func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
