type WorkReport {
  stamps: [Stamp!]!
  workTime: Int!
}

type MonthWorkReportMap {
  key: Int!
  value: WorkReport!
}
type YearReport {
  employmentId: Uint!
  year: Time!
  workReports: [MonthWorkReportMap!]!
}

extend type Query {
  yearReport(companyId: Uint!, year: Time!): YearReport!
}
